#ifndef TM_KIT_BASIC_TRANSACTION_TI_TRANSACTION_TRANSACTION_SERVER_HPP_
#define TM_KIT_BASIC_TRANSACTION_TI_TRANSACTION_TRANSACTION_SERVER_HPP_

#include <tm_kit/basic/transaction/v2/TransactionLogicCombination.hpp>
#include <tm_kit/basic/transaction/TransactionClient.hpp>

#endif